name=TCP9548
version=0.0.2
author=egp
maintainer=egp
sentence=TCA9548/TCA9548A library using TCP3231.
paragraph=Controls the TCA9548/TCA9548A I2C switch using a caller-owned BBI2C bus provided through TCP3231 and TCP1819.
category=Communication
url=https://github.com/egp/TCP9548
architectures=avr,renesas_uno
depends=TCP3231